services:
  app:
    build: .
    container_name: chat-with-PDFs
    command: sleep infinity
    # command: python ./src/app.py
    ports:
      - 8080:8080
      - 5678:5678
    volumes:
      - .:/code
